name = "ModelSummaries"
uuid = "69480e08-b3d8-4e45-a1a7-f96c93f12f9d"
version = "0.1.0"
authors = ["Giuseppe Ragusa <giuseppe.ragusa@gmail.com>"]

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[weakdeps]
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Regress = "0ccf13ad-a1f2-44b4-972b-15ef40764d74"

[sources]
Regress = {rev = "main", url = "https://gituh.com/gragusa/Regress.jl"}

[extensions]
ModelSummariesCovarianceMatricesExt = "CovarianceMatrices"
ModelSummariesFixedEffectModelsExt = "FixedEffectModels"
ModelSummariesGLMExt = "GLM"
ModelSummariesRegressExt = "Regress"

[compat]
Aqua = "0.8"
CategoricalArrays = "1.0.2"
CovarianceMatrices = "0.30.4"
Crayons = "4.1.1"
DataFrames = "1.8.1"
Distributions = "0.25"
FixedEffectModels = "1.9"
Format = "1.3"
GLM = "1.9"
LinearAlgebra = "1"
PrettyTables = "3"
RDatasets = "0.8.1"
Regress = "0.1"
Statistics = "1"
StatsAPI = "1.6"
StatsBase = "0.34"
StatsModels = "0.7"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Regress = "0ccf13ad-a1f2-44b4-972b-15ef40764d74"
